name: Auto PR with GITHUB_TOKEN

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch and make changes
        run: |
          BRANCH="auto-pr-$(date +%s)"
          #git checkout -b $BRANCH
          echo "aaaaaaaaa $(date +%s)" > changes
          #git add .
          #git commit -m "chore: automated update"
          #git push origin $BRANCH
          echo "branch_name=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: update something
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: ${{ env.branch_name }}
          title: "Automated PR by github-actions"
          body: "This PR was automatically created by a workflow."

